# Default configuration values for portal-service
portalService.dbUrl: "postgres://portal_loc_runtime:secret@postgres:5432/configserver"
portalService.hostId: "01964b05-552a-7c4b-9184-6857e7f3dc5f"
server.httpsPort: 2498
server.tlsCertPath: "/config/cert.pem"
server.tlsKeyPath: "/config/key.pem"
server.serviceId: "com.networknt.portal-service-1.0.0"
server.environment: "dev"
server.advertisedAddress: "portal-service"
server.enableRegistry: true
server.startOnRegistryFailure: false

portalRegistry.portalUrl: "https://controller:8438"

client.verifyHostname: false
client.caCertPath: "/keystore/ca.pem"
