---
services:

  hybrid-command:
    volumes:
      - ./hybrid-command/service:/service

  hybrid-query1:
    volumes:
      - ./hybrid-query/service:/service

  hybrid-query2:
    volumes:
      - ./hybrid-query/service:/service

  hybrid-query3:
    volumes:
      - ./hybrid-query/service:/service
