---
services:

  hybrid-command:
    image: ${HYBRID_COMMAND_IMAGE_LOCAL:-portal-config-loc/hybrid-command:2.2.1-local}
    build:
      context: ./hybrid-command
      dockerfile: Dockerfile

  hybrid-query1:
    image: ${HYBRID_QUERY_IMAGE_LOCAL:-portal-config-loc/hybrid-query:2.2.1-local}
    build:
      context: ./hybrid-query
      dockerfile: Dockerfile

  hybrid-query2:
    image: ${HYBRID_QUERY_IMAGE_LOCAL:-portal-config-loc/hybrid-query:2.2.1-local}
    build:
      context: ./hybrid-query
      dockerfile: Dockerfile

  hybrid-query3:
    image: ${HYBRID_QUERY_IMAGE_LOCAL:-portal-config-loc/hybrid-query:2.2.1-local}
    build:
      context: ./hybrid-query
      dockerfile: Dockerfile
