---
services:

  controller:
    image: networknt/light-controller:2.2.1
    volumes:
      - ./light-controller-java/config:/config
    ports:
      - 8438:8438
      # - 5005:5005
    # environment:
    # The following environment variable will enable the debug in the container.
    # JAVA_TOOL_OPTIONS: '-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:5005'
    # restart: on-failure
    hostname: controller
    container_name: controller
    depends_on:
      postgres:
        condition: service_healthy
      light-oauth:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -k -f https://localhost:8438/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

  light-oauth:
    image: networknt/oauth-kafka:2.2.1
    ports:
      - 6881:6881
      # - 5005:5005
    volumes:
      - ./light-oauth-java/config:/config
    # environment:
    # The following environment variable will enable the debug in the container.
    # JAVA_TOOL_OPTIONS: '-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:5005'
    # restart: on-failure
    hostname: light-oauth
    container_name: light-oauth
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -k -f https://localhost:6881/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

  config-server:
    # image: networknt/config-server:2.1.38
    image: networknt/config-server:2.2.1-java
    ports:
      - 8435:8435
      # - 5005:5005
    volumes:
      - ./config-server-java/config:/config
    # environment:
    # The following environment variable will enable the debug in the container.
    # JAVA_TOOL_OPTIONS: '-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:5005'
    # restart: on-failure
    hostname: config-server
    container_name: config-server
    depends_on:
      postgres:
        condition: service_healthy
      controller:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -k -f https://localhost:8435/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

  portal-service:
    image: networknt/light-reference:2.2.1
    ports:
      - 2498:2498
    volumes:
      - ./portal-service-java/config:/config
      - /home/steve/data:/data
    # environment:
    #   JAVA_TOOL_OPTIONS: '-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:5005'
    # restart: on-failure
    hostname: portal-service
    container_name: portal-service
    networks:
      default:
        aliases:
          - reference
    depends_on:
      postgres:
        condition: service_healthy
      config-server:
        condition: service_healthy
