version: "2"

services:
  config-server:
    image: networknt/config-server:2.1.31
    volumes:
      - ./config-server:/config
    ports:
      - 8435:8435
    hostname: config-server
    container_name: config-server
    networks:
      - localnet
networks:
  localnet:
    # driver: bridge
    external: true
