version: '3.1'
services:
  oauth-kafka:
    image: networknt/oauth-kafka:2.1.35
    # ports:
    #   - "6881:6881"
    volumes:
      - ./config:/config
    container_name: oauth-kafka
    network_mode: host
    # networks:
    #   - localnet
# networks:
#   localnet:
#     # driver: bridge
#     external: true
