services:
  oauth-kafka:
    # image: networknt/oauth-kafka:2.1.38
    image: networknt/oauth-kafka:2.1.38-slim
    # ports:
    #   - "6881:6881"
    volumes:
      - ./config:/config
    environment:
      # The following environment varialbe will enable the debug in the container.
      JAVA_TOOL_OPTIONS: '-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005'

    container_name: oauth-kafka
    network_mode: host
    # networks:
    #   - localnet
# networks:
#   localnet:
#     # driver: bridge
#     external: true
