version: '2'
services:
  oauth-code:
    image: networknt/oauth-code:2.0.32
    ports:
      - "6881:6881"
    volumes:
      - ./oauth-code:/config
    extra_hosts:
      - "oauth.lightapi.net:${DOCKER_HOST_IP}"
    environment:
      - STATUS_HOST_IP=${DOCKER_HOST_IP}
    hostname: oauth-code
    container_name: oauth-code
    networks:
      - localnet
  oauth-token:
    image: networknt/oauth-token:2.0.32
    ports:
      - "6882:6882"
    volumes:
      - ./oauth-token:/config
    extra_hosts:
      - "oauth.lightapi.net:${DOCKER_HOST_IP}"
    environment:
      - STATUS_HOST_IP=${DOCKER_HOST_IP}
    hostname: oauth-token
    container_name: oauth-token
    networks:
      - localnet
  oauth-key:
    image: networknt/oauth-key:2.0.32
    ports:
      - "6886:6886"
    volumes:
      - ./oauth-key:/config
    extra_hosts:
      - "oauth.lightapi.net:${DOCKER_HOST_IP}"
    environment:
      - STATUS_HOST_IP=${DOCKER_HOST_IP}
    hostname: oauth-key
    container_name: oauth-key
    networks:
      - localnet
networks:
  localnet:
    # driver: bridge
    external: true
