# server.yml
server.httpsPort: 8441
server.serviceId: com.networknt.portal.hybrid.query-1.0.0

# client.yml
client.verifyHostname: false
client.tokenAcClientId: f7d42348-c647-4efb-a52d-4c5787421e73
client.tokenCcClientId: f7d42348-c647-4efb-a52d-4c5787421e73
client.tokenRtClientId: f7d42348-c647-4efb-a52d-4c5787421e73
client.tokenKeyClientId: f7d42348-c647-4efb-a52d-4c5787421e73
client.signClientId: f7d42348-c647-4efb-a52d-4c5787421e73
client.signKeyClientId: f7d42348-c647-4efb-a52d-4c5787421e73
client.derefClientId: f7d42348-c647-4efb-a52d-4c5787421e73
client.injectOpenTracing: true

# kafka-streams.yml
kafka-streams.bootstrap.servers: localhost:9092
kafka-streams.schema.registry.url: http://localhost:8081
# kafka-streams.cleanUp: true

# portal.yml
portal.sendEmail: false
portal.cmdHost: https://localhost:8439
portal.resetHost: https://devsignin.lightapi.net

# db-provider.yml
# For postgres database running in a docker container, you have to use the driverClassName.
db-provider.driverClassName: org.postgresql.Driver
db-provider.jdbcUrl: jdbc:postgresql://localhost:5432/configserver
db-provider.username: postgres
db-provider.password: secret
db-provider.maximumPoolSize: 3

# cache.yml
cache.caches:
  - cacheName: portal-data
    expiryInMinutes: 60
    maxSize: 1000
  - cacheName: auth_code
    expiryInMinutes: 5
    maxSize: 1000

# direct-registry.yml
direct-registry.directUrls:
  com.networknt.portal.hybrid.query-1.0.0: https://localhost:8440,https://localhost:8441,https://localhost:8442
  com.networknt.portal.hybrid.command-1.0.0: https://localhost:8439
  com.networknt.oauth-kafka-1.0.0: https://localhost:6881
  com.networknt.reference-1.0.0: https://localhost:2498

# service.yml
service.singletons:
  - com.networknt.registry.URL:
    - com.networknt.registry.URLImpl
  - com.networknt.registry.Registry:
    - com.networknt.registry.support.DirectRegistry
  - com.networknt.balance.LoadBalance:
    - com.networknt.balance.RoundRobinLoadBalance
  - com.networknt.cluster.Cluster:
    - com.networknt.cluster.LightCluster
  - com.networknt.cache.CacheManager:
    - com.networknt.cache.CaffeineCacheManager
  # PortalDbProviderImpl of DbProvider
  - com.networknt.db.provider.DbProvider:
    - net.lightapi.portal.db.PortalDbProviderImpl
  # StartupHookProvider implementations, there are one to many and they are called in the same sequence defined.
  - com.networknt.server.StartupHookProvider:
    # registry all service handlers by from annotations
    - com.networknt.rpc.router.RpcStartupHookProvider
    # - com.networknt.jaeger.tracing.JaegerStartupHookProvider
    # User Query Startup Hook
    - net.lightapi.portal.user.query.UserQueryStartup
    # Covid Query Startup Hook
    # - net.lightapi.portal.covid.query.CovidQueryStartup
    # Market Query Startup Hook
    - net.lightapi.portal.market.query.MarketQueryStartup
    # database startup hook to initialize datasource and cache.
    - com.networknt.db.provider.SqlDbStartupHook
  # ShutdownHookProvider implementations, there are one to many and they are called in the same sequence defined.
  - com.networknt.server.ShutdownHookProvider:
    # User Query Shutdown Hook
    - net.lightapi.portal.user.query.UserQueryShutdown
    # Covid Query Shutdown Hook
    # - net.lightapi.portal.covid.query.CovidQueryShutdown
    # Market Query Shutdown Hook
    - net.lightapi.portal.market.query.MarketQueryShutdown
  # Schema Registry client implementation
  - io.confluent.kafka.schemaregistry.client.SchemaRegistryClient:
    - com.networknt.kafka.common.LightSchemaRegistryClient

# cors.yml
cors.enabled: true
cors.allowedOrigins:
  - https://localhost:3000
  - https://lightapi.net
  - https://dev.lightapi.net
cors.allowedMethods:
  - GET
  - POST
  - PUT
  - DELETE

# hybrid-security.yml
hybrid-security.enableVerifyJwt: false
