# server.yml
server.httpsPort: 2498

# db-provider.yml
# For postgres database running in a docker container, you have to use the driverClassName.
db-provider.driverClassName: org.postgresql.Driver
db-provider.jdbcUrl: jdbc:postgresql://timescale:5432/configserver
db-provider.username: postgres
db-provider.password: secret
db-provider.maximumPoolSize: 3

# service.yml
service.singletons:
  - com.networknt.db.provider.DbProvider:
    - com.networknt.reference.ReferenceDbProviderImpl
  - com.networknt.server.StartupHookProvider:
    - com.networknt.db.provider.SqlDbStartupHook
  - com.networknt.cache.CacheManager:
    - com.networknt.cache.CaffeineCacheManager

# openapi-security.yml
openapi-security.enableVerifyJwt: false

# cors.yml
cors.allowedOrigins:
  - https://devsignin.lightapi.net
  - https://dev.lightapi.net
  - https://dev.maproot.net
  - https://devsignin.maproot.net
  - https://localhost:3000
cors.allowedMethods:
  - GET
  - POST
  - PUT
  - DELETE
  - PATCH
  - OPTIONS

# reference.yml
reference.dataPath: /data

# metrics.yml
metrics.enabled: false

# cache.yml
cache.caches:
  - cacheName: jwt
    expiryInMinutes: 15
    maxSize: 100
  - cacheName: jwk
    expiryInMinutes: 129600
    maxSize: 100
  - cacheName: ref-data
    expiryInMinutes: 60
    maxSize: 1000
