# controller.yml
controller.listenAddress: 0.0.0.0:8438
controller.microserviceJwksUrl: https://light-oauth:6881/oauth2/AZZRJE52eXu3t1hseacnGQ/keys
controller.jwksVerifyHostname: false
controller.databaseDriverClassName: org.postgresql.Driver
controller.databaseUrl: jdbc:postgresql://postgres:5432/configserver
controller.databaseUsername: postgres
controller.databasePassword: secret
