# server.yml
server.httpsPort: 8443
server.serviceId: com.networknt.http-sidecar-1.0.0

# client.yml
client.verifyHostname: false
client.tokenServerUrl: https://oauth-kafka:6881
# JSON Web Key
client.tokenKeyServerUrl: https://oauth-kafka:6881
client.tokenKeyUri: /oauth2/N2CMw0HGQXeLvC1wBfln2A/keys

# proxy yml
proxy.hosts: https://openapi-petstore:9443

# service.yml
service.singletons:
  - com.networknt.registry.URL:
    - com.networknt.registry.URLImpl
  - com.networknt.registry.Registry:
    - com.networknt.registry.support.DirectRegistry
  - com.networknt.balance.LoadBalance:
    - com.networknt.balance.RoundRobinLoadBalance
  - com.networknt.cluster.Cluster:
    - com.networknt.cluster.LightCluster
  - com.networknt.handler.ResponseInterceptor:
    - com.networknt.body.ResponseBodyInterceptor
    - com.networknt.restrans.ResponseTransformerInterceptor
  - com.networknt.handler.RequestInterceptor:
    - com.networknt.body.RequestBodyInterceptor
    - com.networknt.reqtrans.RequestTransformerInterceptor
  - com.networknt.cache.CacheManager:
    - com.networknt.cache.CaffeineCacheManager
  - com.networknt.server.StartupHookProvider:
    - com.networknt.rule.RuleLoaderStartupHook


# handler.yml
handler.enabled: true
handler.basePath: /v1
handler.handlers:
  # Light-framework cross-cutting concerns implemented in the microservice
  - com.networknt.exception.ExceptionHandler@exception
  - com.networknt.metrics.MetricsHandler@metrics
  - com.networknt.traceability.TraceabilityHandler@traceability
  - com.networknt.correlation.CorrelationHandler@correlation
  # Cors handler to handler post/put pre-flight. It is not used in the sidecar but only in the router.
  # - com.networknt.cors.CorsHttpHandler@cors
  - com.networknt.openapi.OpenApiHandler@specification
  - com.networknt.openapi.JwtVerifyHandler@security
  - com.networknt.body.BodyHandler@body
  - com.networknt.audit.AuditHandler@audit
  # DumpHandler is to dump detail request/response info to log, useful for troubleshooting but not suggested to use in production due to it may lower the performance
  # - com.networknt.dump.DumpHandler@dump
  - com.networknt.sanitizer.SanitizerHandler@sanitizer
  - com.networknt.openapi.ValidatorHandler@validator
  # Header middleware to manipulate request and/or response headers before or after downstream server
  - com.networknt.header.HeaderHandler@header
  # Rate limit middleware to prevent DDoS attacks externally or throttle requests internally
  - com.networknt.limit.LimitHandler@limit
  # Direct requests to named services based on the request path
  - com.networknt.router.middleware.SidecarPathPrefixServiceHandler@path
  - com.networknt.router.middleware.SidecarTokenHandler@token
  - com.networknt.router.SidecarRouterHandler@router
  - com.networknt.proxy.LightProxyHandler@proxy
  - com.networknt.openapi.AccessControlHandler@access
  # Customer business domain specific cross-cutting concerns handlers
  # - com.example.validator.CustomizedValidator@custvalidator
  # Framework endpoint handlers
  # Control Pane middleware handlers and API handler
  - com.networknt.chaos.KillappAssaultHandler@killapp
  - com.networknt.chaos.LatencyAssaultHandler@latency
  - com.networknt.chaos.MemoryAssaultHandler@memory
  - com.networknt.chaos.ExceptionAssaultHandler@exchaos
  - com.networknt.chaos.ChaosMonkeyGetHandler@chaosget
  - com.networknt.chaos.ChaosMonkeyPostHandler@chaospost
  - com.networknt.proxy.ProxyHealthGetHandler@proxyHealth
  - com.networknt.health.HealthGetHandler@health
  - com.networknt.proxy.ProxyServerInfoHandler@info
  - com.networknt.cache.CacheExplorerHandler@cache
  - com.networknt.logging.handler.LoggerGetHandler@getLogger
  - com.networknt.logging.handler.LoggerPostHandler@postLogger
  - com.networknt.logging.handler.LoggerGetLogContentsHandler@getLogContents
  - com.networknt.config.reload.handler.ModuleRegistryGetHandler@modules
  - com.networknt.config.reload.handler.ConfigReloadHandler@configReload
  - com.networknt.specification.SpecDisplayHandler@spec
  - com.networknt.specification.SpecSwaggerUIHandler@swaggerui
  - com.networknt.specification.FaviconHandler@favicon
  - com.networknt.handler.ResponseInterceptorInjectionHandler@responseInterceptor
  - com.networknt.handler.RequestInterceptorInjectionHandler@requestInterceptor
  - com.networknt.server.handler.ServerShutdownHandler@shutdown

handler.chains.default:
  - exception
  # - metrics
  - limit
  - traceability
  - correlation
  - killapp
  - latency
  - memory
  - exchaos
  # - cors
  - header
  - requestInterceptor
  - responseInterceptor
  # Outgoing traffic does not need to use security and validator. Just get the token and call the router.
  - path
  - audit
  - token
  - router
  - specification
  - security
  - access
  - sanitizer
  - validator
  - proxy

# security.yml
security.enableVerifyJwt: true

# request-injection.yml
request-injection.appliedBodyInjectionPathPrefixes:
  - /

# response-injection.yml
response-injection.appliedBodyInjectionPathPrefixes:
  - /

# response-transformer.yml
response-transformer.appliedPathPrefixes:
  - /

# request-transformer.yml
request-transformer.appliedPathPrefixes:
  - /

# header.yml
header.enabled: true
header.response.update: Cache-Control:no-store,X-Content-Type-Options:nosniff

# body.yml
body.logFullRequestBody: true
body.logFullResponseBody: true

# cache.yml
cache.caches:
  - cacheName: jwt
    expiryInMinutes: 15
    maxSize: 100
  - cacheName: jwk
    expiryInMinutes: 129600
    maxSize: 100

# chaos-monkey.yml
chaos-monkey.enabled: true

# latency-assault.yml
latency-assault.enabled: true

# rule-loader.yml
portal.authorization: eyJraWQiOiI3cEdITG96R1JYcXYyZzQ3VDFIUWFnIiwiYWxnIjoiUlMyNTYifQ.eyJpc3MiOiJ1cm46Y29tOm5ldHdvcmtudDpvYXV0aDI6djEiLCJhdWQiOiJ1cm46Y29tLm5ldHdvcmtudCIsImV4cCI6MjA1MTU2NjM3OCwianRpIjoicXhhNFl6ZFhJWWptaHZXbDRhU2YwQSIsImlhdCI6MTczNjIwNjM3OCwibmJmIjoxNzM2MjA2MjU4LCJ2ZXIiOiIxLjAiLCJjaWQiOiJmN2Q0MjM0OC1jNjQ3LTRlZmItYTUyZC00YzU3ODc0MjFlNzMiLCJzY3AiOlsicG9ydGFsLnIiLCJwb3J0YWwudyJdfQ.ccERu3HgYOoLpIspR2zZOLaGPL1C6jhu9giDJK3eG1EIkia5iAF8n7a-m3aImhxFivSBcgDrXxIEKuiR_Wc3PMwFGhX7g15NcHHXtRc_U-MbzTxoUzSARRXCrnke9AjxAdAcRBNQwhQ48pCGYze2WzHODFvwJ2qthg8cGiLDa_XiKRAEUM1aeX1goXSfhxHxc4VZbhtMj7YBeSKzvw0MTmazf6ibnoM7X1Ha2vOfRimOochpEMyJfHbXcQRfL-yNIpFljg6lbA2TGW4EaPJIM8S9NTILHboi192BNM5VDGhV2Djk2bcy_GD80jyqijwxzb13-I9ET5W5anNe-yZ3CA
rule-loader.portalHost: https://light-gateway:8443
