# Server configuration
dbUrl: ${db_url}
port: ${server_port}
hostId: ${host_id}
tlsCertPath: ${tls_cert_path}
tlsKeyPath: ${tls_key_path}
jwtIssuer: ${jwt_issuer}
jwtAudience: ${jwt_audience}
msalJwksUrl: ${msal_jwks_url}
msalJwksAcceptInvalidCerts: ${msal_jwks_accept_invalid_certs}
msalJwtExpectedIssuer: ${msal_jwt_expected_issuer}
msalJwtExpectedAudience: ${msal_jwt_expected_audience}
ccacJwksUrl: ${ccac_jwks_url}
ccacJwksAcceptInvalidCerts: ${ccac_jwks_accept_invalid_certs}
ccacJwtExpectedIssuer: ${ccac_jwt_expected_issuer}
ccacJwtExpectedAudience: ${ccac_jwt_expected_audience}
