---
version: '3.1'
services:
  controller-node1:
    image: networknt/light-controller:2.1.37
    volumes:
      - ./config/node1:/config
    # ports:
    #   - 8438:8438
    hostname: controller-node1
    container_name: controller-node1
    network_mode: host
    # networks:
    #   - localnet

  controller-node2:
    image: networknt/light-controller:2.1.37
    volumes:
      - ./config/node2:/config
    # ports:
    #   - 8437:8437
    hostname: controller-node2
    container_name: controller-node2
    network_mode: host
    # networks:
    #   - localnet

  controller-node3:
    image: networknt/light-controller:2.1.37
    volumes:
      - ./config/node3:/config
    # ports:
    #   - 8436:8436
    hostname: controller-node3
    container_name: controller-node3
    network_mode: host
    # networks:
    #   - localnet

# networks:
#   localnet:
#     # driver: bridge
#     external: true
