services:

  light-gateway:
    image:  networknt/light-gateway:2.1.38-slim
    # ports:
    #   - 8443:8443
    #   - 5005:5005
    volumes:
      - ./config:/config
      - ./lightapi/dist:/lightapi/dist
      - ./signin/dist:/signin/dist
    environment:
      STATELESSAUTH_BOOTSTRAPTOKEN: ${STATELESSAUTH_BOOTSTRAPTOKEN}
      STATELESSAUTH_GITHUBCLIENTSECRET: ${STATELESSAUTH_GITHUBCLIENTSECRET}
      STATELESSAUTH_GOOGLECLIENTSECRET: ${STATELESSAUTH_GOOGLECLIENTSECRET}
      STATELESSAUTH_FACEBOOKCLIENTSECRET: ${STATELESSAUTH_FACEBOOKCLIENTSECRET}
      # The following environment varialbe will enable the debug in the container.
      # JAVA_TOOL_OPTIONS: '-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005'
    container_name: light-gateway
    network_mode: host
    # networks:
    #   - localnet

  # reference API
  reference:
    # image: networknt/com.networknt.reference:2.1.38
    image: networknt/com.networknt.reference:2.1.38-slim
    volumes:
      - ./reference:/config
      - /home/steve/data:/data
    environment:
      JAVA_TOOL_OPTIONS: '-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005'

    container_name: reference
    network_mode: host

  # petstore API for testing control pane.
  # petstore:
  #   image: networknt/com.networknt.petstore-3.0.1:2.1.0
  #   ports:
  #     - 9443:9443
  #   volumes:
  #     - ./petstore:/config
  #   hostname: petstore
  #   container_name: petstore
  #   networks:
  #     - localnet

# networks:
#   localnet:
#     # driver: bridge
#     external: true
