version: "3.1"
#
# Services
#
services:
  hybrid-command:
    image: networknt/portal-hybrid-command:2.1.31
    environment:
      - NOREPLAY_EMAIL_PASSWORD=${NOREPLAY_EMAIL_PASSWORD}
    volumes:
      - ./hybrid-command/config:/config
      - ./hybrid-command/service:/service
      - /home/steve/data:/data
    # ports:
    #   - 8439:8439
    container_name: hybrid-command
    network_mode: host
    # networks:
    #   - localnet

  hybrid-query1:
    image: networknt/portal-hybrid-query:2.1.31-slim
    volumes:
      - ./hybrid-query/node1:/config
      - ./hybrid-query/service:/service
      - /home/steve/data:/data
    # ports:
    #   - 8440:8440
    container_name: hybrid-query1
    network_mode: host
    # networks:
    #   - localnet

  hybrid-query2:
    image: networknt/portal-hybrid-query:2.1.31-slim
    volumes:
      - ./hybrid-query/node2:/config
      - ./hybrid-query/service:/service
      - /home/steve/data:/data
    # ports:
    #   - 8441:8441
    container_name: hybrid-query2
    network_mode: host
    # networks:
    #   - localnet

  hybrid-query3:
    image: networknt/portal-hybrid-query:2.1.31-slim
    volumes:
      - ./hybrid-query/node3:/config
      - ./hybrid-query/service:/service
      - /home/steve/data:/data
    # ports:
    #   - 8442:8442
    container_name: hybrid-query3
    network_mode: host
    # networks:
    #   - localnet


# networks:
#   localnet:
#     # driver: bridge
#     external: true
