#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat >&2 <<'USAGE'
usage: render-schema.sh COMPONENT SCHEMA [OUTPUT]

COMPONENT is one of:
  configserver     Portal/config-server final-state DDL
  bootstrap        Portal bootstrap data
  knowledge        Light-Knowledge final-state DDL
  knowledge-roles  Light-Knowledge cluster-role bootstrap

SCHEMA must be an unquoted PostgreSQL identifier. Multi-environment installs
should use configserver_<environment> and knowledge_<environment>.
USAGE
  exit 2
}

[[ $# -ge 2 && $# -le 3 ]] || usage

component="$1"
schema_name="$2"
output_file="${3:-}"
script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
postgres_dir="$(cd -- "$script_dir/.." && pwd)"

if [[ ! "$schema_name" =~ ^[a-z][a-z0-9_]{0,62}$ ]]; then
  echo "render-schema: invalid schema name '$schema_name'; use 1-63 lowercase letters, digits, and underscores" >&2
  exit 2
fi

case "$schema_name" in
  public|pg_catalog|information_schema|extensions)
    echo "render-schema: protected schema '$schema_name' cannot be an application schema" >&2
    exit 2
    ;;
esac

case "$component" in
  configserver)
    source_file="${PORTAL_DB_CONFIGSERVER_SOURCE:-$postgres_dir/ddl.sql}"
    expected_prefix="configserver"
    ;;
  bootstrap)
    source_file="${PORTAL_DB_BOOTSTRAP_SOURCE:-$postgres_dir/init-lightapi.sql}"
    expected_prefix="configserver"
    ;;
  knowledge)
    source_file="${PORTAL_DB_KNOWLEDGE_SOURCE:-$postgres_dir/knowledge/ddl.sql}"
    expected_prefix="knowledge"
    ;;
  knowledge-roles)
    source_file="${PORTAL_DB_KNOWLEDGE_ROLES_SOURCE:-$postgres_dir/knowledge/roles.sql}"
    expected_prefix="knowledge"
    ;;
  *)
    echo "render-schema: unknown component '$component'" >&2
    usage
    ;;
esac

if [[ ! -f "$source_file" ]]; then
  echo "render-schema: source file does not exist: $source_file" >&2
  exit 2
fi

if [[ "$schema_name" != "$expected_prefix" && "$schema_name" != "$expected_prefix"_* ]]; then
  echo "render-schema: component '$component' requires schema '$expected_prefix' or '${expected_prefix}_<environment>'" >&2
  exit 2
fi

role_suffix=""
if [[ "$expected_prefix" == "knowledge" && "$schema_name" == knowledge_* ]]; then
  role_suffix="${schema_name#knowledge_}"
  longest_role_name="light_knowledge_${role_suffix}_schema_migration_role"
  if [[ ${#longest_role_name} -gt 63 ]]; then
    echo "render-schema: Knowledge environment suffix is too long for generated PostgreSQL role names" >&2
    exit 2
  fi
fi

render() {
  printf '%s\n' \
    "-- Generated by postgres/bin/render-schema.sh; do not edit." \
    "-- Component: $component" \
    "-- Application schema: $schema_name" \
    "SET search_path = $schema_name, public;"

  if [[ "${PORTAL_DB_STRIP_TOP_LEVEL_TRANSACTIONS:-false}" == "true" ]]; then
    sed -e '/^BEGIN;$/d' -e '/^COMMIT;$/d' "$source_file"
  else
    cat "$source_file"
  fi | sed \
    -e '/^CREATE DATABASE configserver;$/d' \
    -e '/^\\c configserver;$/d' \
    -e '/^\\connect configserver;$/d' \
    -e 's/public\.vector_cosine_ops/__PORTAL_DB_EXTENSION_SCHEMA__.vector_cosine_ops/g' \
    -e 's/public\.vector_dims/__PORTAL_DB_EXTENSION_SCHEMA__.vector_dims/g' \
    -e 's/public\.gin_trgm_ops/__PORTAL_DB_EXTENSION_SCHEMA__.gin_trgm_ops/g' \
    -e 's/public\.gist_trgm_ops/__PORTAL_DB_EXTENSION_SCHEMA__.gist_trgm_ops/g' \
    -e 's/public\.vector/__PORTAL_DB_EXTENSION_SCHEMA__.vector/g' \
    -e "s/public\./${schema_name}./g" \
    -e "s/\\(nspname[[:space:]]*=[[:space:]]*\\)'public'/\\1'${schema_name}'/g" \
    -e "s/DEFAULT 'public'::character varying/DEFAULT '${schema_name}'::character varying/g" \
    -e "/^[[:space:]]*\\(parent_schema\\|child_schema\\)[[:space:]]/s/DEFAULT 'public'/DEFAULT '${schema_name}'/g" \
    -e "s/\\(\\(parent_schema\\|child_schema\\)[[:space:]]*=[[:space:]]*\\)'public'/\\1'${schema_name}'/g" \
    -e "/^[[:space:]]*('public',/s/'public'/'${schema_name}'/g" \
    -e "s/SELECT pg_catalog.set_config('search_path', '', false);/SET search_path = ${schema_name}, public;/g" \
    -e "s/ON SCHEMA public/ON SCHEMA ${schema_name}/g" \
    -e "s/Name: SCHEMA public/Name: SCHEMA ${schema_name}/g" \
    -e "s/Schema: public/Schema: ${schema_name}/g" \
    -e 's/__PORTAL_DB_EXTENSION_SCHEMA__/public/g' |
    if [[ -n "$role_suffix" ]]; then
      sed \
        -e "s/light_knowledge_schema_migration_role/light_knowledge_${role_suffix}_schema_migration_role/g" \
        -e "s/light_knowledge_snapshot_loader_role/light_knowledge_${role_suffix}_snapshot_loader_role/g" \
        -e "s/light_knowledge_admin_api_role/light_knowledge_${role_suffix}_admin_api_role/g" \
        -e "s/light_knowledge_ops_read_role/light_knowledge_${role_suffix}_ops_read_role/g" \
        -e "s/light_knowledge_worker_role/light_knowledge_${role_suffix}_worker_role/g" \
        -e "s/light_knowledge_api_role/light_knowledge_${role_suffix}_api_role/g"
    else
      cat
    fi
}

if [[ -z "$output_file" || "$output_file" == "-" ]]; then
  render
else
  output_dir="$(dirname -- "$output_file")"
  mkdir -p -- "$output_dir"
  temporary_output="$(mktemp "$output_dir/.render-schema.XXXXXX")"
  trap 'rm -f -- "$temporary_output"' EXIT
  render >"$temporary_output"
  mv -- "$temporary_output" "$output_file"
  trap - EXIT
fi
