ip: ${server_ip:0.0.0.0}
httpPort: ${server_http_port:8080}
enableHttp: ${server_enable_http:false}
httpsPort: ${server_port}
enableHttps: ${server_enable_https:true}
tlsCertPath: ${tls_cert_path:/config/cert.pem}
tlsKeyPath: ${tls_key_path:/config/key.pem}
serviceId: ${server_service_id:com.networknt.reference-1.0.0}
enableRegistry: ${server_enable_registry:false}
startOnRegistryFailure: ${server_start_on_registry_failure:true}
dynamicPort: ${server_dynamic_port:false}
environment: ${server_environment:dev}
shutdownGracefulPeriod: ${server_shutdown_graceful_period:2000}
