# Singleton service factory configuration/IoC injection
singletons:
- com.networknt.registry.URL:
  - com.networknt.registry.URLImpl:
      parameters:
        com.networknt.portal.hybrid.query-1.0.0: https://192.168.1.102:8440,https://192.168.1.102:8441,https://192.168.1.102:8442
        com.networknt.portal.hybrid.command-1.0.0: https://192.168.1.102:8439
        com.networknt.oauth-key-1.0.0: https://192.168.1.102:6886
        com.networknt.oauth-token-1.0.0: https://192.168.1.102:6882
        com.networknt.oauth-code-1.0.0: https://192.168.1.102:6881
        com.networknt.reference-1.0.0: https://192.168.1.102:2498
- com.networknt.registry.Registry:
  - com.networknt.registry.support.DirectRegistry
- com.networknt.balance.LoadBalance:
  - com.networknt.balance.RoundRobinLoadBalance
- com.networknt.cluster.Cluster:
  - com.networknt.cluster.LightCluster
- com.networknt.server.StartupHookProvider:
  - com.networknt.jaeger.tracing.JaegerStartupHookProvider
