version: '3.1'

services:

  light-router:
    image:  networknt/light-router:2.1.0
    ports:
      - 8443:8443
    volumes:
      - ./config:/config
      - ./lightapi/build:/lightapi/build
      - ./signin/build:/signin/build
    environment:
      STATELESS_AUTH_BOOTSTRAP_TOKEN: ${STATELESS_AUTH_BOOTSTRAP_TOKEN}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      FACEBOOK_CLIENT_SECRET: ${FACEBOOK_CLIENT_SECRET}
    hostname: light-router
    container_name: light-router
    networks:
      - localnet

  # reference API
  reference:
    image: networknt/com.networknt.reference-1.0.0:2.1.30
    ports:
      - 2498:2498
    volumes:
      - ./reference:/config
      - /home/steve/data:/data
    # depends_on:
    #   - timescale
    hostname: reference
    container_name: reference
    networks:
      - localnet

  # petstore API for testing control pane.
  # petstore:
  #   image: networknt/com.networknt.petstore-3.0.1:2.1.0
  #   ports:
  #     - 9443:9443
  #   volumes:
  #     - ./petstore:/config
  #   hostname: petstore
  #   container_name: petstore
  #   networks:
  #     - localnet

networks:
  localnet:
    # driver: bridge
    external: true
